---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: export-service
  labels:
    prometheus: app-sre
    role: alert-rules
spec:
  groups:
  - name: export-service-prod
    rules:

    - alert: ExportServiceAvailability
      expr: sum(rate(api_3scale_gateway_api_status{status="5xx",exported_service="export"}[5m])) / sum(rate(api_3scale_gateway_api_status{exported_service="export"}[5m])) > 0.05
      labels:
        #TODO: add a working prometheus rules test to increase severity again
        severity: medium
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/ir5blOCVk/exportservice-dashboard?orgId=1&viewPanel=12&var-datasource=crcp01ue1-prometheus"
        link_url: "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/export-service-prod/deployments"
        message: "Export Service Alert. Availability < 95% in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/export-service/App-export-service-In-export-service-prod-availability.rst"

    - alert: ExportServiceLatency
      expr: sum(rate(api_3scale_gateway_api_time_bucket{le="0500.0", exported_service="export"}[5m])) / sum(rate(api_3scale_gateway_api_time_bucket{le="+Inf", exported_service="export"}[5m])) < .9
      labels:
        #TODO: add a working prometheus rules test to increase severity again
        severity: medium
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/ir5blOCVk/exportservice-dashboard?orgId=1&var-datasource=crcp01ue1-prometheus&editPanel=14"
        link_url:  "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/export-service-prod/deployments"
        message: "Export Service Alert. More than 10% of requests with Latency > 500ms in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/export-service/App-export-service-In-export-service-prod-latency.rst"

    - alert: ExportServiceErrorRate
      expr: (sum(rate(export_service_http_requests_total{container="export-service-service", path="", code="5.*"}[5m]) or vector(0)) / (sum(rate(export_service_http_requests_total{container="export-service-service", path=""}[5m])) + 0.00001)) > 0.05
      labels:
        #TODO: add a working prometheus rules test to increase severity again
        severity: medium
        service: insights
        env: prod
        app_team: data-pipeline
      annotations:
        dashboard: "https://grafana.app-sre.devshift.net/d/ir5blOCVk/exportservice-dashboard?orgId=1&var-datasource=crcp01ue1-prometheus&viewPanel=18"
        link_url:  "https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/export-service-prod/deployments"
        message: "Export Service Alert. Error rate > 5% in prod environment."
        runbook: "https://gitlab.cee.redhat.com/service/app-interface/-/tree/master/docs/console.redhat.com/app-sops/export-service/App-export-service-In-export-service-prod-error-rate.rst"
